version: '3'

services:
    python:
        image: python:3.6
        volumes:
            - ./ADS-PIII:/ADS-PIII
        ports:
            - 8000:8000
        command: bash -c "cd ADS-PIII && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"